### PR TITLE
 Add support for projects that use the monorepo approach #82

### PR DESCRIPTION
**Pull request by girsan1**

### CODE REVIEW

**Comment by girsan1** [comment]
@shiouen I added support for #83. Could you review my changes?

**Comment by menathan** [comment]
+1: I believe this is a great addition.

If a prefix or suffix is configured, then sbot predictions will always be based on the latest semver tag including that prefix or suffix.

Note: Implements #82

**Comment by menathan** [comment]
This should be considered a patch, rather than minor version. See my comment at #82

**Comment by shiouen** [comment]
Hi @girsan1 & @menathan 

I like the addition of support for a monorepo, the only thing I am slightly worried about is that if someone decides to no longer use a specific prefix, e.g. migrating away from "v" as a prefix to "" or vice versa, `sbot` will start over from 0 again. Not the smoothest experience for users.

I also notice that the PR contains a hardcoded prefix = "v" condition. What if the user uses another prefix?

I think we might need a bit of a different approach here, e.g. a --repo=[mono|multi] where multi is the default, adjustable through the config file as well, so the flag does not have to be provided every time. Thoughts?

**Comment by girsan1** [comment]
Hi @shiouen, 
>I am slightly worried about is that if someone decides to no longer use a specific prefix, e.g. migrating away from "v" as a >prefix to "" or vice versa, sbot will start over from 0 again. Not the smoothest experience for users.
>
Yes, it will start from 0 but only for any other prefixes except "v". For "v" prefix it will work as current release. Actually, in current release for example prefix="some_project" will not work too and start from 0.
>
> I also notice that the PR contains a hardcoded prefix = "v" condition. What if the user uses another prefix?
> 
Yes, I added it to have backward compatibility since I see "v" is considered as a default and can be replaced with just version X.X.X without prefix(https://github.com/restechnica/semverbot/blob/2dbd6a1d2df3375028bb54c104a353cfc7bf80bc/pkg/semver/parse.go#L14
https://github.com/blang/semver/blob/4487282d78122a245e413d7515e7c516b70c33fd/v4/semver.go#L242). So if prefix = "v" then we will work as before changes, means vX.X.X == X.X.X for semverbot. 
>
>I think we might need a bit of a different approach here, e.g. a --repo=[mono|multi] where multi is the default, adjustable >through the config file as well, so the flag does not have to be provided every time. Thoughts?
>
Yes, it also can be an option to implement it in this way. But definitely it will require more changes and efforts.

**Comment by menathan** [comment]
@shiouen, image a scenario where you would move from "v" to no prefix "" (empty string), and where the latest tag is for example "v2.4.5". In that case you would change the prefix in `.semverbot.toml` from "v" to "" and manually create a git tag "2.4.5" so that versioning wouldn't start from the beginning. Wouldn't that work, or did you mean something else?

**Comment by menathan** [comment]
I opened a new PR #84 that deals with the suffix differently that the prefix in find/matching the version.

**Comment by girsan1** [comment]
close this PR since @menathan open new one with these changes inside.

**Pull request closed without merging**
